### PR TITLE
consumer: order-of-operations for messagesReceived

### PR DESCRIPTION
**Pull request by qianlnk**
1、messagesReceived should be add after message had transport to message channel.

2、 add Consume method,use Consume to get message channel if someone want to custom  `ack` or `nack`.

### CODE REVIEW

**Comment by mreiferson** [comment]
@qianlnk thanks for the PR, but I don't actually understand the bug. Also, for numerous reasons, it's not safe to expose the go channel over which messages are delivered, so we wouldn't merge that API addition.

**Comment by qianlnk** [comment]
@mreiferson We can't receive the message from message channel until the message transfer to message channel(because the message channel may be blocked). I hold the opinion  that count of `messagesReceived` should be put after the message transfer to message channel. as for  the user, `messagesReceived` must be equal to the number received from message handler.

**Comment by ploxiln** [comment]
You propose to not increment `messagesReceived` until the handler starts processing the message. I think the original intention is to count the message received as soon as the process receives it from nsqd (and I think this is even more important for `totalRdyCount`).

**Comment by qianlnk** [comment]
ok, I know what you mean. But when I run `consume.Stop` and get `ConsumerStats` by `Stats` method，I find that `stats.MessagesReceived` != `stats.MessagesFinished` + `stats.MessagesRequeued` sometime. if `messagesReceived` increase here,  `messagesRequeued` should also increase when the `Stop`?

**Comment by ploxiln** [comment]
hmm ... I think it might be possible that some messages could be received by the consumer process from nsqd, just after Stop() is called and `incomingMessages` is closed, and we could possibly handle it more elegantly, though it's a tricky distributed timing problem ... what you could do is call [ChangeMaxInFlight(0)](https://godoc.org/github.com/nsqio/go-nsq#Consumer.ChangeMaxInFlight) and wait a couple seconds, then call `Stop()`, and in that case you should get consistent numbers, and no dropped messages

**Pull request closed without merging**
