### PR TITLE
dep; update .travis.yml

### PR DESCRIPTION
**Pull request by judwhite**
Use [`dep`](https://github.com/golang/dep) for dependency management.

Two reasons:
- `dep` is likely the future de-facto community standard (though I'm still a fan of [`govendor`](https://github.com/kardianos/govendor))
- `gpm` doesn't work well with Windows; or Windows doesn't work well with `gpm`, take your pick 😄 ([see issues](https://github.com/pote/gpm/issues?utf8=%E2%9C%93&q=is%3Aissue%20windows))

Per the `dep` [README](https://github.com/golang/dep/blob/b926156450482283e2c484c3b51f31919019ab6e/README.md#current-status):

> dep is still changing rapidly. If you need stability (e.g. for CI), it's best to rely on a released version, not tip.

Given this advice, added the following to `.travis.yml`:
```
  - wget -O dep https://github.com/golang/dep/releases/download/v0.3.2/dep-linux-amd64
  - chmod +x dep
  - ./dep ensure
```

to replace:

```
  - go get github.com/golang/snappy
```

Note `revision = "d9eb7a3d35ec988b8585d4a0068e462c27d28380"` is taken from [nsqio/nsq/Godeps#L6](https://github.com/nsqio/nsq/blob/220ca470508c2aafdc53a3e92b48d5a6e144185b/Godeps#L6). You could also specify `branch = "master"` (or `version = "x.y.z"` if tags exist and you trust semver), which would mimic the `go get` command but would differ from `nsqio/nsq`.

Added `go 1.9.x` to `.travis.yml`.

Similar PR coming for `nsqio/nsq` if this approach works.

RFR @mreiferson @jehiah @ploxiln

### CODE REVIEW

**Comment by mreiferson** [comment]
this is great, thanks @judwhite!

want to squash down?

**Comment by mreiferson** [comment]
Actually, one question — `dep` supports libraries, not just binaries?

**Comment by judwhite** [comment]
@mreiferson Yes it does. If you use `dep` to import a library which also uses `dep`, it reads its `Gopkg.toml` to determine which ones you need to resolve. How it deals with conflicts I haven't read about yet, but I know you can override your deps' deps with whatever revision you want.

Squash merge, or do you prefer a merge commit?

**Comment by mreiferson** [comment]
squash merge

**Comment by ploxiln** [comment]
@mreiferson IIRC you previously/typically had the opposite preference - manual squash then merge commit, over github-squash-merge no-merge-commit?

**Comment by mreiferson** [comment]
I misunderstood, since he can’t merge the PR, and I had asked, that he could only be talking about what do do with the commits in this branch.

**Comment by judwhite** [comment]
@mreiferson Squashed.

**Pull request merged**
